import {BilingualText} from "@/components/language";
import {EditorialPage,InfoBand} from "@/components/editorial";
import {createRouteMetadata} from "@/lib/seo";
import {AnswerPanel} from "@/components/answer-panel";

export const metadata=createRouteMetadata("/one-way-travel");

export default function Page(){
  return <EditorialPage eyebrow={<BilingualText en="One-way travel" mr="एकमार्गी प्रवास"/>} title={<BilingualText en="One clear" mr="एक स्पष्ट"/>} accent={<BilingualText en="route." mr="मार्ग."/>} intro={<BilingualText en="Send a point-to-point travel enquiry when your journey does not need a return trip." mr="तुमच्या प्रवासासाठी परतीचा मार्ग आवश्यक नसल्यास एका ठिकाणाहून दुसऱ्या ठिकाणापर्यंतच्या प्रवासाची चौकशी पाठवा."/>} visual="/generated/one-way.webp" serviceLabel="One-way Travel">
    <section className="route-strip"><div className="shell route-strip-inner"><span><BilingualText en="START" mr="सुरुवात"/></span><i></i><strong><BilingualText en="Your pickup · your destination" mr="तुमचे पिकअप · तुमचे ठिकाण"/></strong><i></i><span><BilingualText en="ARRIVE" mr="पोहोचा"/></span></div></section>
    <InfoBand eyebrow={<BilingualText en="For a journey that ends there" mr="परतीचा प्रवास नसलेल्या प्रवासासाठी"/>} title={<><BilingualText en="Pickup to destination." mr="पिकअपपासून गंतव्यापर्यंत."/><br/><em><BilingualText en="No return leg." mr="परतीचा टप्पा नाही."/></em></>} copy={<BilingualText en="Use a one-way enquiry when you need to travel from one place to another without including a return journey in the same request." mr="त्याच विनंतीमध्ये परतीचा प्रवास नसताना एका ठिकाणाहून दुसऱ्या ठिकाणी जाण्यासाठी एकमार्गी चौकशी वापरा."/>} items={[<BilingualText key="a" en="Exact pickup location" mr="अचूक पिकअप ठिकाण"/>,<BilingualText key="b" en="Exact drop destination" mr="अचूक ड्रॉप ठिकाण"/>,<BilingualText key="c" en="Preferred travel date" mr="पसंतीची प्रवास तारीख"/>,<BilingualText key="d" en="Number of passengers" mr="प्रवाशांची संख्या"/>]}/>
    <section className="shell traveller-grid"><div><p className="eyebrow"><BilingualText en="Common one-way requirements" mr="सामान्य एकमार्गी गरजा"/></p><h2><BilingualText en="One destination. " mr="एक गंतव्य. "/><em><BilingualText en="Different reasons to travel." mr="प्रवासाची वेगवेगळी कारणे."/></em></h2><p className="muted-copy"><BilingualText en="The same point-to-point enquiry can cover an individual, a family or a larger group. The form keeps the route and passenger information together." mr="एकाच ठिकाणाहून दुसऱ्या ठिकाणापर्यंतची चौकशी व्यक्ती, कुटुंब किंवा मोठ्या गटासाठी असू शकते. फॉर्ममध्ये मार्ग आणि प्रवाशांची माहिती एकत्र राहते."/></p></div><div className="traveller-cards"><article><strong><BilingualText en="City to city" mr="शहर ते शहर"/></strong><p><BilingualText en="A single intercity journey without a return leg in the same request." mr="त्याच विनंतीमध्ये परतीचा टप्पा नसलेला एक शहरांतर प्रवास."/></p></article><article><strong><BilingualText en="Family travel" mr="कुटुंबाचा प्रवास"/></strong><p><BilingualText en="Send the pickup, destination, date and total number of passengers together." mr="पिकअप, गंतव्य, तारीख आणि एकूण प्रवाशांची संख्या एकत्र पाठवा."/></p></article><article><strong><BilingualText en="Group travel" mr="गट प्रवास"/></strong><p><BilingualText en="Use the passenger count and additional details to explain the group requirement." mr="गटाची गरज स्पष्ट करण्यासाठी प्रवाशांची संख्या आणि अतिरिक्त तपशील वापरा."/></p></article></div></section>
    <AnswerPanel intent="oneWay"/>
  </EditorialPage>;
}
