"use client";
import Image, {type StaticImageData} from "next/image";
import {useEffect,useRef} from "react";
import {siteMedia} from "@/lib/media";
type MediaRecord={frame:HTMLElement;layer:HTMLElement;active:boolean};
const records=new Set<MediaRecord>(); let raf=0; let observer:IntersectionObserver|undefined; let listening=false;
const schedule=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;const h=innerHeight;const travel=innerWidth<=760?8:innerWidth<=1100?13:18;records.forEach(r=>{if(!r.active)return;const b=r.frame.getBoundingClientRect();const p=(b.top+b.height/2-h/2)/(h/2+b.height/2);r.layer.style.transform=`translate3d(0,${Math.max(-1,Math.min(1,p))*travel}px,0)`;r.layer.style.willChange="transform"})})};
const start=()=>{if(listening)return;listening=true;observer=new IntersectionObserver(entries=>{entries.forEach(e=>{const r=[...records].find(x=>x.frame===e.target);if(r){r.active=e.isIntersecting;if(!e.isIntersecting)r.layer.style.willChange="auto"}});schedule()},{rootMargin:"160px 0px"});records.forEach(r=>observer?.observe(r.frame));addEventListener("scroll",schedule,{passive:true});addEventListener("resize",schedule,{passive:true})};
const stop=()=>{if(records.size||!listening)return;removeEventListener("scroll",schedule);removeEventListener("resize",schedule);observer?.disconnect();observer=undefined;listening=false;if(raf)cancelAnimationFrame(raf);raf=0};
const replacements:Record<string,StaticImageData>={"/generated/homepage.webp":siteMedia.ellora,"/generated/ajanta.webp":siteMedia.ajanta,"/generated/ellora.webp":siteMedia.ellora,"/generated/ghrishneshwar.webp":siteMedia.ghrishneshwar,"/generated/trimbakeshwar.webp":siteMedia.trimbakeshwar,"/generated/bhimashankar.webp":siteMedia.bhimashankar,"/generated/one-way.webp":siteMedia.oneWay,"/generated/corporate.webp":siteMedia.corporate};
export function ParallaxMedia({src,alt,className="",sizes,priority=false,loading,children}:{src:StaticImageData|string;alt:string;className?:string;sizes:string;priority?:boolean;loading?:"eager"|"lazy";children?:React.ReactNode}){const frame=useRef<HTMLDivElement>(null);const layer=useRef<HTMLDivElement>(null);const imageSrc=typeof src==="string"?replacements[src]??src:src;useEffect(()=>{const f=frame.current,l=layer.current;if(!f||!l||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r={frame:f,layer:l,active:false};records.add(r);start();observer?.observe(f);schedule();return()=>{observer?.unobserve(f);records.delete(r);l.style.willChange="auto";l.style.transform="";stop()}},[]);return <div ref={frame} className={`parallax-media ${className}`}><div ref={layer} className="parallax-media__layer"><Image src={imageSrc} alt={alt} fill sizes={sizes} placeholder={typeof imageSrc==="string"?"empty":"blur"} preload={priority} loading={priority?loading:undefined}/></div>{children}</div>}
