import {BilingualText} from "@/components/language";
import {EditorialPage,InfoBand} from "@/components/editorial";
import {createRouteMetadata} from "@/lib/seo";
import {AnswerPanel} from "@/components/answer-panel";

export const metadata=createRouteMetadata("/corporate-travel");

export default function Page(){
  return <EditorialPage eyebrow={<BilingualText en="Corporate transportation" mr="कॉर्पोरेट वाहतूक"/>} title={<BilingualText en="Plan team" mr="टीमच्या"/>}accent={<BilingualText en="movement." mr="प्रवासाची चौकशी."/>} intro={<BilingualText en="Discuss regular employee pickup, drop, office-route and shift transportation requirements for your company." mr="तुमच्या कंपनीसाठी नियमित कर्मचारी पिकअप, ड्रॉप, ऑफिस मार्ग आणि शिफ्ट वाहतुकीच्या गरजांबद्दल चर्चा करा."/>} visual="/generated/corporate.webp" serviceLabel="Corporate Transportation">
    <InfoBand eyebrow={<BilingualText en="For companies and their people" mr="कंपन्या आणि त्यांच्या कर्मचाऱ्यांसाठी"/>} title={<><BilingualText en="Discuss regular movement." mr="नियमित प्रवासाबद्दल चर्चा करा."/></>} copy={<BilingualText en="Enquire about buses for employee pickup and drop, office routes, shift movement or recurring company transportation. Share the route and schedule so the practical requirement can be reviewed." mr="कर्मचारी पिकअप आणि ड्रॉप, ऑफिस मार्ग, शिफ्ट प्रवास किंवा नियमित कंपनी वाहतुकीसाठी बसबद्दल चौकशी करा. व्यावहारिक गरज पाहण्यासाठी मार्ग आणि वेळापत्रक सांगा."/>} items={[<BilingualText key="a" en="Employee bus route enquiries" mr="कर्मचारी बस मार्गांच्या चौकश्या"/>,<BilingualText key="b" en="Pickup and drop requirements" mr="पिकअप आणि ड्रॉपच्या गरजा"/>,<BilingualText key="c" en="Shift transportation requirements" mr="शिफ्ट वाहतुकीच्या गरजा"/>,<BilingualText key="d" en="Recurring company requirements" mr="नियमित कंपनी गरजा"/>]}/>
    <section className="workday-band"><div className="shell"><p className="eyebrow"><BilingualText en="A company route, discussed" mr="कंपनीच्या मार्गाची चर्चा"/></p><h2><BilingualText en="From first pickup" mr="पहिल्या पिकअपपासून"/><br/><em><BilingualText en="to final drop." mr="अंतिम ड्रॉपपर्यंत."/></em></h2><div className="timeline"><div><span><BilingualText en="Route details" mr="मार्गाचे तपशील"/></span><strong><BilingualText en="Share the stops" mr="थांबे सांगा"/></strong><p><BilingualText en="Share employee areas, pickup points, office location and preferred departure time." mr="कर्मचाऱ्यांचे परिसर, पिकअप ठिकाणे, ऑफिसचे ठिकाण आणि पसंतीची सुटण्याची वेळ सांगा."/></p></div><div><span><BilingualText en="Schedule details" mr="वेळापत्रकाचे तपशील"/></span><strong><BilingualText en="Describe the shifts" mr="शिफ्ट सांगा"/></strong><p><BilingualText en="Include office commute or shift transportation requirements for the working day." mr="कामाच्या दिवसासाठी ऑफिस प्रवास किंवा शिफ्ट वाहतुकीच्या गरजा सांगा."/></p></div><div><span><BilingualText en="Ongoing need" mr="सततची गरज"/></span><strong><BilingualText en="Review changes" mr="बदलांचा आढावा"/></strong><p><BilingualText en="Discuss recurring requirements and changes as your company routes evolve." mr="कंपनीचे मार्ग बदलत असताना नियमित गरजा आणि बदलांबद्दल चर्चा करा."/></p></div></div></div></section>
    <section className="shell service-detail-grid corporate-details"><div><p className="eyebrow"><BilingualText en="What to include" mr="काय सांगावे"/></p><h2><BilingualText en="Useful details." mr="उपयुक्त तपशील."/><br/><em><BilingualText en="Better planning." mr="अधिक चांगले नियोजन."/></em></h2></div><div className="detail-list"><div><strong><BilingualText en="Company details" mr="कंपनीचे तपशील"/></strong><span><BilingualText en="Organisation name and contact person." mr="संस्थेचे नाव आणि संपर्क व्यक्ती."/></span></div><div><strong><BilingualText en="Route and shifts" mr="मार्ग आणि शिफ्ट"/></strong><span><BilingualText en="Pickup/drop area, office location and shift timings." mr="पिकअप/ड्रॉप परिसर, ऑफिसचे ठिकाण आणि शिफ्टच्या वेळा."/></span></div><div><strong><BilingualText en="Scale of service" mr="सेवेचा आवाका"/></strong><span><BilingualText en="Approximate employees, stops and buses required." mr="अंदाजे कर्मचारी, थांबे आणि आवश्यक बसची संख्या."/></span></div></div></section>
    <AnswerPanel intent="corporate"/>
  </EditorialPage>;
}
